dirs:
  - .
excludedDirs:
  - vendor
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
  - 206
  - 429
ignorePatterns:
  - pattern: "^https://localhost"
  - pattern: "^https://github.com/orgs/zaphiro-technologies/"
  - pattern: "^https://github.com/zaphiro-technologies/"
